### ISSUE TITLE
Update algolia/algoliasearch-client-php ^3.x

### ISSUE THREAD

**Issue by Stalex89** [studioespresso/craft-scout#192] opened 2021-07-21 13:42 UTC
I'm getting this error when trying to update algolia/algoliasearch-client-php to version 3.0.1
Is it related to the rias/craft-scout plugin dependencies? Thank you

Composer output: Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

Problem 1
- rias/craft-scout is locked to version 2.4.0 and an update of this package was not requested.
- Conclusion: don't install algolia/algoliasearch-client-php 2.7.3 (conflict analysis result)
- Conclusion: don't install algolia/algoliasearch-client-php 3.0.2 (conflict analysis result)
- Conclusion: don't install algolia/algoliasearch-client-php 2.8.0 (conflict analysis result)
- Root composer.json requires trendyminds/algolia 3.0.1 -> satisfiable by trendyminds/algolia[3.0.1].
- rias/craft-scout 2.4.0 requires algolia/algoliasearch-client-php ^2.3 -> satisfiable by algolia/algoliasearch-client-php[2.3.0, ..., 2.8.0].
- You can only install one version of a package, so only one of these can be installed: algolia/algoliasearch-client-php[2.3.0, ..., 2.8.0, 3.0.0, 3.0.1, 3.0.2].
- trendyminds/algolia 3.0.1 requires algolia/algoliasearch-client-php ^3.0 -> satisfiable by algolia/algoliasearch-client-php[3.0.0, 3.0.1, 3.0.2].
- Conclusion: don't install algolia/algoliasearch-client-php 3.0.1 (conflict analysis result)

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.

![Screenshot 2021-07-21 at 15 41 19](https://user-images.githubusercontent.com/23526237/126498483-67613c12-aeeb-4c13-a1bc-d86858f4df8e.png)

**Comment by janhenckens** [comment] 2021-08-03 15:38
algolia/algoliasearch-client-php 3.0.0 is a breaking change from 2.x and it drops support for PHP < 7.2.

That would be a significant change for us too so marking this for plugin version 3.0.0 at minimum.

**Comment by bymayo** [comment] 2021-09-14 10:39
@janhenckens Any idea when 3.0 will be released? Currently can't update any other Algolia plugins to the latest versions because of this change. I get the same error.

**Comment by janhenckens** [comment] 2021-09-20 06:29
Looking into it this week! algolia/algoliasearch-client-php 3.0.0 doesn't actually change anything, they only dropped support for PHP 7.2. And given that we're (finally ™) adding PHP 8 support (#210), this might be a good time to do both.

**Comment by janhenckens** [comment] 2021-09-28 18:53
@bymayo @Stalex89 

I'm going to combine this with a release that supports PHP 8 or higher (supports, not requires).
If you'd like you can try the branch to see if it installs on your environments. You can do that by changing the line for the package in your composer.json to:

`"studioespresso/craft-scout": "dev-php8 as 2.5.0"`

And then running `composer update`. Could you give that a try and let me know if it works?

**Comment by goraxan** [comment] 2021-11-27 19:37
@janhenckens I can confirm both plugins are now compatible with the dev-php8 branch, thanks!

**Comment by janhenckens** [comment] 2021-11-30 09:27
@goraxan Thanks! Merging this this week together with  #210.

**Comment by fantasticmachine** [comment] 2021-12-06 14:26
@janhenckens can this get merged/released? I'm trying to get a site up to date and can't currently install Scout and Algolia plugins together because of this conflict.

**Comment by janhenckens** [comment] 2021-12-06 15:05
@fantasticmachine Been trying to get tests working with the algolia 3.x, hoping to have it out very soon!

**Comment by fantasticmachine** [comment] 2021-12-06 15:13
Is there any way I can work around it for the short term? I tried installing using "studioespresso/craft-scout": "dev-php8 as 2.5.0" but get different errors

Problem 1
    - Root composer.json requires studioespresso/craft-scout dev-php8 as 2.5.0, found studioespresso/craft-scout[dev-dependabot/composer/tightenco/collect-tw-8.0.0, dev-dependabot/composer/tightenco/collect-tw-8.0.4, dev-feature/gh-actions, dev-override-batch-size, dev-master, dev-develop, dev-97-multisite-single-index, 0.1.1, ..., 0.4.2, 1.0.0, ..., 1.3.2, 2.0.0, ..., 2.5.0] but it does not match the constraint.

**Comment by janhenckens** [comment] 2021-12-06 18:53
@fantasticmachine It's out in 2.6.0, you can give it a try!

**Closed** 2021-12-07 17:44 UTC
Labels: dependencies, 🚨 breaking change
