### ISSUE TITLE
Call to a member function getPaymentCurrencies() on null

### ISSUE THREAD

**Issue by brambeekman** [studioespresso/craft-scout#195] opened 2021-07-25 09:16 UTC
When using scout to make an index with products it gives this error `Call to a member function getPaymentCurrencies() on null`

```

 \rias\scout\ScoutIndex::create('market')
            // Scout uses this by default, so this is optional
            ->elementType(\craft\commerce\elements\Product::class)
            // If you don't define a siteId, the primary site is used
            ->criteria(function (\craft\commerce\elements\db\ProductQuery $query) {
                return $query->type('beers');
            })
            /*
             * The element gets passed into the transform function, you can omit this
             * and Scout will use the \rias\scout\ElementTransformer class instead
            */
            ->transformer(function (\craft\commerce\elements\Product $product) {

            })
            /*
             * You can use this to define index settings that get synced when you call
             * the ./craft scout/settings/update console command. This way you can
             * keep your index settings in source control. The IndexSettings
             * object provides autocompletion for all Algolia's settings
            */
            ->indexSettings(
                \rias\scout\IndexSettings::create()
                    ->minWordSizefor1Typo(4)
            ),

```

**Comment by janhenckens** [comment] 2021-08-05 19:04
Duplicate of #178, closing this issue.

**Closed by janhenckens** 2021-08-05 19:04 UTC
Labels: 📦 commerce
